import os

SERVER_IP = os.environ['LABML_APP_SERVER_IP']
PORT = os.environ['LABML_APP_SERVER_PORT']
SERVER_URL = f'http://{SERVER_IP}:{PORT}'
WEB_URL = f'http://{SERVER_IP}:{PORT}'

SLACK_BOT_TOKEN = ''
SLACK_CHANNEL = ''
SENTRY_DSN = ''
FLOAT_PROJECT_TOKEN = 'floating_project'
SAMPLES_PROJECT_TOKEN = 'samples'
LABML_VERSION = '0.4.112'
ANALYTICS_TO_SERVER = False
IS_LOCAL_SETUP = True
INDICATOR_LIMIT = 100
IS_LOGIN_REQUIRED = False
EMAIL_AWS_REGION = ''
EMAIL_SENDER = ''
EMAIL_CHARSET = 'UTF-8'
