export const AUTH0_DOMAIN = 'auth0.com'
export const AUTH0_CLIENT_ID = ''
export const APP_BASE_URL = 'http://localhost:5000'
export const API_BASE_URL = 'http://localhost:5000/api/v1'
export const MOBILE_APP_NAMESPACE = ''
export const SENTRY_DSN = ''
